/*
 *   This file will be regenerated by `mulle-sourcetree-to-c --project-dialect objc` via
 *   `mulle-sde reflect` and any edits will be lost.
 *   Suppress generation of this file with:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_IMPORT_FILE DISABLE
 *
 *   To not let mulle-sourcetree-to-c generate any header files:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_RUN DISABLE
 *
 */

// You can tweak the following #import with these commands.
// (Use 3C44D901-1A8E-4B88-9A06-A26FA13F4D86 instead of MulleFoundationBase if there are duplicate entries)
//    remove #import: : `mulle-sde dependency mark MulleFoundationBase no-header`
//    rename:              `mulle-sde dependency|library set MulleFoundationBase include whatever.h`
//    reorder:             `mulle-sde dependency move MulleFoundationBase <up|down>`
//    toggle #import:     `mulle-sde dependency mark MulleFoundationBase [no-]import`
//    toggle public:       `mulle-sde dependency mark MulleFoundationBase [no-]public`
//    toggle optional:     `mulle-sde dependency mark MulleFoundationBase [no-]require`
//    remove for platform: `mulle-sde dependency mark MulleFoundationBase no-platform-<uname>`
//        (use `mulle-sourcetree-to-c --unames` to list known values)
#import <MulleFoundationBase/MulleFoundationBase.h>   // MulleFoundationBase

#ifdef __has_include
# if __has_include( "_MulleScionHTMLPreprocessor-include.h")
#  include "_MulleScionHTMLPreprocessor-include.h"
# endif
#endif

